# Generated by Django 4.1.5 on 2023-02-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="studends",
        ),
        migrations.AlterField(
            model_name="detected",
            name="time_stamp",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
